# Owner: S2
# Tool: TFLite → C array converter
# Usage: python tools/tflite_to_cc.py
# Input:  ml/models/naad_kws_int8.tflite
# Output: firmware/kws_tflm/kws_model_data.cc

import os

INPUT  = "ml/models/naad_kws_int8.tflite"
OUTPUT = "firmware/kws_tflm/kws_model_data.cc"

os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)

with open(INPUT, "rb") as f:
    data = f.read()

# Format bytes as C hex array
hex_values = ", ".join(f"0x{b:02x}" for b in data)

# Wrap at 12 bytes per line for readability
bytes_per_line = 12
chunks = [data[i:i+bytes_per_line] for i in range(0, len(data), bytes_per_line)]
hex_lines = ",\n  ".join(
    ", ".join(f"0x{b:02x}" for b in chunk)
    for chunk in chunks
)

cc_content = f"""// AUTO-GENERATED by tools/tflite_to_cc.py — DO NOT EDIT MANUALLY
// Source: {INPUT}
// Size:   {len(data)} bytes ({len(data)/1024:.1f} KB)
// Model:  Project NAAD DS-CNN KWS INT8

#include "kws_model.h"

alignas(8) const uint8_t kws_model_data[] = {{
  {hex_lines}
}};

const int kws_model_data_len = {len(data)};
"""

with open(OUTPUT, "w") as f:
    f.write(cc_content)

print(f"Generated: {OUTPUT}")
print(f"Model size: {len(data)} bytes ({len(data)/1024:.1f} KB)")
print(f"Array name: kws_model_data[{len(data)}]")
